name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  REGISTRY: registry.noverhead.de

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login private registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login "$REGISTRY" -u "${{ secrets.REGISTRY_USER }}" --password-stdin
      - name: Build image
        run: docker build -t "$REGISTRY/${{ github.event.repository.name }}:latest" .
      - name: Push image
        run: docker push "$REGISTRY/${{ github.event.repository.name }}:latest"
